### ISSUE TITLE
session handleOpen should detect if Accept has been called 

### ISSUE THREAD

**Issue by progrium** [progrium/qtalk-go#19]
when a new incoming channel is handled, we just throw it into the inbox channel, but if Accept as not been called, then the client side will just block indefinitely with no error. this happens often when a Peer is created without running the Respond() goroutine, which is easy to forget. if we create state indicating the Accept has been called, we can see when an incoming channel comes in if there is nothing accepting and return a useful open failure message that should error the client side.

**Comment by mgood** [comment]
Yeah it looks like even though the `inbox` channel is buffered, `handleOpen` will still block until there's a spot in the buffer.

IIUC your suggestion is to detect if `Accept` has never been called, then once it has, assume that it will eventually get to accepting new requests. Does it make sense to include a timeout on waiting for that first `Accept` to avoid race conditions?

Though I guess in addition it seems like adding channels to the inbox should return an error if the buffer is full.

Once the server has started `Accept`ing channels, would it make sense to have another timeout to ensure that the current channel has been accepted before returning `OpenConfirmMessage`? Or maybe it's better to assume that it *will* be handled at some point to let the client start sending messages sooner?

**Comment by progrium** [comment]
ok, looks like the inbox channel is buffered and it doesn't need to be. some carry over from porting from ssh maybe. if we set it to zero (no real reason to not be, other than it makes this code work), then it seems like things make more sense: try to put new channel into inbox, only send `OpenConfirmMessage` when it goes through, have a timeout that sends a failure. this way not calling `Accept` means it will timeout and the client *should* get an error.
