### ISSUE TITLE
fix error when response is too big

### ISSUE THREAD

**Issue by progrium** [progrium/qtalk-go#20]
tracked down an EOF error that turned out to not be a session/connection EOF but a channel EOF because the response object was too large. not sure where it broke from size (serialize, buffer, send), but does and a client EOF is not very helpful. however, i'm not sure we can do much better in terms of improving the error, but we should be able to fix it. 

this might have been from a maximum packet size limitation (which has since been increased for now), which should be tracked down. maximum packet size shouldn't truncate data, but just make several Write calls. i suspect this complicates reading JSON values because the codec probably assumes one object per data message? maybe not. just need to make sure this doesn't break reading JSON values.

**Comment by mgood** [comment]
I started trying some tests to see if I can hit this. I came across one issue here, where if the encoded size overflows uint32, this size prefix will be incorrect:
https://github.com/progrium/qtalk-go/blob/0e87838b26a3e447e15e6ac9d82f12a601d5f9b0/rpc/frame.go#L41-L42
Could it have been that large, or was this with something a bit smaller?
With that one we can error-out if the encoded value is too large, though increasing the size would require some change to the protocol to support larger lengths.

**Comment by progrium** [comment]
It was definitely not over 4 gigabytes. IIRC, the max packet size constant was cutting it off so I just increased that to something arbitrarily high. I'm going to say we should not worry about single messages/objects being over 4 gigs right now. But in regard to max packet size, wouldn't you expect if a message was too big it would split it over several data messages? Presumably data is being buffered and reading it would continue to work? Anyway, try setting max packet size const to something really low and see what happens.

**Comment by mgood** [comment]
Yeah, I started off with some changes like that just setting smaller packet sizes and wasn't initially reproducing it until I hit that issue above. So it seemed like it was doing the right thing in splitting messages, but I can poke at it a little more and see if I find anything else.

**Comment by progrium** [comment]
No, good enough for me for now.
