### ISSUE TITLE
GH Actions run 2x for PRs

### ISSUE THREAD

**Issue by mgood** [progrium/qtalk-go#28]
I noticed that with the PR it's running doubling up the Actions for both the `push` and `pull_request`.

For the moment it doesn't seem like a priority, but it will burn through the GH Actions free credits faster, so may need to be fixed if the project is running low on credits.

**Comment by progrium** [comment]
good catch, esp since we have some ... racey code that doesn't benefit from being run more than it should to fail checks. maybe we just do `pull_request`

**Comment by mgood** [comment]
Hmm, maybe something like this would give the right combination to run only on pushes to master or on pull requests, but not overlapping:
https://stackoverflow.com/a/70767151

**Comment by mgood** [comment]
I wonder if it's also worth persisting the test cache so that it doesn't re-run tests which have a cached result.
